name: Test GMP Cellar on macOS 14

on:
  workflow_dispatch:

jobs:
  test-gmp:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check initial GMP cellar
      run: |
        echo "=== Initial check for /opt/homebrew/Cellar/gmp ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install git
      run: brew install git
      
    - name: Check GMP cellar after git
      run: |
        echo "=== Check after installing git ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install bison
      run: brew install bison
      
    - name: Check GMP cellar after bison
      run: |
        echo "=== Check after installing bison ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install autoconf
      run: brew install autoconf
      
    - name: Check GMP cellar after autoconf
      run: |
        echo "=== Check after installing autoconf ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install automake
      run: brew install automake
      
    - name: Check GMP cellar after automake
      run: |
        echo "=== Check after installing automake ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install libffi
      run: brew install libffi
      
    - name: Check GMP cellar after libffi
      run: |
        echo "=== Check after installing libffi ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""
      
    - name: Install findutils
      run: brew install findutils
      
    - name: Check GMP cellar after findutils
      run: |
        echo "=== Check after installing findutils ==="
        if [ -d /opt/homebrew/Cellar/gmp ]; then
          echo "GMP cellar exists:"
          ls -la /opt/homebrew/Cellar/gmp
          echo "Subfolders:"
          find /opt/homebrew/Cellar/gmp -type d -maxdepth 1
        else
          echo "GMP cellar does NOT exist"
        fi
        echo ""