name: sysconfig-macos-arm64

on:
  workflow_dispatch:

jobs:
  run-sysconfig:
    runs-on: macos-14
    steps:
      - name: Install Python 3.11
        run: brew install python@3.11
      - name: Run python -m sysconfig
        run: python3.11 -m sysconfig