name: sysconfig-macos-arm64

on:
  workflow_dispatch:

jobs:
  run-sysconfig:
    runs-on: macos-14
    steps:
      - name: Print default PATH
        run: echo $PATH
      - name: Install zstd from arm brew
        run: brew install zstd
      - name: Print path to zstd installed from brew
        run: which zstd
      - name: Install Intel brew
        run: arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install zstd on Intel brew
        run: arch -x86_64 /usr/local/bin/brew install zstd
      - name: Print Intel zstd path
        run: arch -x86_64 which zstd
      - name: Print new PATH
        run: echo $PATH