name: sysconfig-macos-arm64

on:
  workflow_dispatch:

jobs:
  run-sysconfig:
    runs-on: macos-14
    steps:
      - name: Print default PATH
        run: echo $PATH
      - name: Install zstd from arm brew
        run: brew install zstd
      - name: Print path to zstd installed from brew
        run: brew --prefix zstd
      - name: List contents of arm zstd path
        run: ls $(brew --prefix zstd)
      - name: Install Intel brew
        run: arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install zstd on Intel brew
        run: arch -x86_64 /usr/local/bin/brew install zstd
      - name: Print Intel zstd path
        run: arch -x86_64 /usr/local/bin/brew --prefix zstd
      - name: List contents of Intel zstd path
        run: arch -x86_64 ls $(/usr/local/bin/brew --prefix zstd)
      - name: Print new PATH
        run: echo $PATH
      - name: Check pkg-config version
        run: pkg-config --version
      - name: Print pkg-config pc_path
        run: echo $PKG_CONFIG_PATH
      - name: Get pkg-config pc_path variable
        run: pkg-config --variable pc_path pkg-config
      - name: Check zstd in /usr/local/lib
        run: ls -la /usr/local/lib/ | grep zstd || echo "No zstd in /usr/local/lib"
      - name: Check zstd in /usr/local/include
        run: ls -la /usr/local/include/ | grep zstd || echo "No zstd in /usr/local/include"