name: Test Python Download on macOS 14

on:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and extract Python
      run: |
        mkdir -p /Users/runner/work/IfcOpenShell/IfcOpenShell/build/Darwin/x86_64/10.15/install
        cd /Users/runner/work/IfcOpenShell/IfcOpenShell/build/Darwin/x86_64/10.15/install
        curl -L -o cache-python-3.9.11.tar.gz https://github.com/IfcOpenShell/build-outputs/raw/refs/heads/macos-x64/Darwin/x86_64/10.15/install/cache-python-3.9.11.tar.gz
        tar -xzf cache-python-3.9.11.tar.gz

    - name: Test Python version
      run: |
        /Users/runner/work/IfcOpenShell/IfcOpenShell/build/Darwin/x86_64/10.15/install/python-3.9.11/bin/python3.9 --version